codecov:
  require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  range: "0..100"

  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

fixes:
  - "*/organizadorCampeanatoBrasileiro/::organizadorCampeanatoBrasileiro/"
  - "*/tests/::tests/"

comment:
  layout: "header, diff, files"
  behavior: default
  require_changes: no

ignore:
  - "tests/**"
  - "README.md"
  - "setup.py"
